apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-analytics
  template:
    metadata:
      labels:
        app: retail-analytics
    spec:
      containers:
      - name: retail-analytics
        image: retail-analytics:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 4040

---
apiVersion: v1
kind: Service
metadata:
  name: retail-analytics-service
spec:
  selector:
    app: retail-analytics
  type: NodePort
  ports:
  - port: 4040
    targetPort: 4040
    nodePort: 30080
