apiVersion: apps/v1
kind: Deployment

metadata:
  name: retail-analytics

spec:
  replicas: 1

  selector:
    matchLabels:
      app: retail-analytics

  template:
    metadata:
      labels:
        app: retail-analytics

    spec:
      containers:
        - name: retail-analytics
          image: retail-analytics:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 4040

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"

            limits:
              memory: "2Gi"
              cpu: "1"
